change rootfs

diff --git a/firmware/buildroot/package/openvpn/S60openvpn b/firmware/buildroot/package/openvpn/S60openvpn
--- a/firmware/buildroot/package/openvpn/S60openvpn
+++ b/firmware/buildroot/package/openvpn/S60openvpn
@@ -11,15 +11,13 @@ CONFIG_DIR=/etc/openvpn
 test -d $CONFIG_DIR || exit 0
 
 start_vpn () {
-    printf " $NAME "
-    start-stop-daemon -S -p /var/run/openvpn.$NAME.pid -x /usr/sbin/openvpn -- \
-	      --daemon --writepid /var/run/openvpn.$NAME.pid \
-	      --config $CONFIG_DIR/$NAME.conf --cd $CONFIG_DIR
-    [ $? = 0 ] && echo "OK" || echo "FAIL"
+    /usr/sbin/openvpn --daemon --writepid /var/run/openvpn.$NAME.pid \
+            --config $CONFIG_DIR/$NAME.conf --cd $CONFIG_DIR || printf " FAILED->"
+    printf " $NAME"
 }
 stop_vpn () {
-    printf " $NAME "
-    start-stop-daemon -K -p /var/run/openvpn.$NAME.pid -x /usr/sbin/openvpn
+   kill `cat $PIDFILE` || true
+  rm $PIDFILE
 }
 
 case "$1" in
@@ -50,6 +48,7 @@ stop)
       NAME=`echo $PIDFILE | cut -c18-`
       NAME=${NAME%%.pid}
       stop_vpn
+      printf " $NAME"
     done
   else
     if test -e /var/run/openvpn.$2.pid ; then
@@ -57,6 +56,7 @@ stop)
       NAME=`echo $PIDFILE | cut -c18-`
       NAME=${NAME%%.pid}
       stop_vpn
+      printf " $NAME"
     else
       printf " No such VPN: $2"
     fi
